import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'UnderKey',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body>{children}</body>
    </html>
  )
} 